# Use root/example as user/password credentials
# docker stack deploy -c stack.yml mysql (or docker-compose -f stack.yml up)
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    volumes:
      - 'f:/databases/mysqldb/:/var/lib/mysql'
    env_file:
      - 'i:/docker_op/mysql_test/vars.env'
    ports:
      - 3306:3306
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
